### ISSUE TITLE
øsnker doc: useFeature generic T

### ISSUE THREAD

**Issue by ArianMathai** [kristiania-kws2100-2024/kristiania-kws2100-2024.github.io#2]
https://github.com/kristiania-kws2100-2024/kristiania-kws2100-2024.github.io/blob/8b91b3111e2cafa9e4fd163a6f0f2d2b565d11fa/src/modules/map/useFeatures.tsx#L8

Kunne du lagt inn en kommentar som forklarer bruken av T?

**Comment by jhannes** [comment]
Lagt inn her: https://github.com/kristiania-kws2100-2024/kristiania-kws2100-2024.github.io/blob/reference/05/src/modules/map/useVectorFeatures.tsx
