### ISSUE TITLE
ønsker doc: hva betyr "layerPredicate"?

### ISSUE THREAD

**Issue by ArianMathai** [kristiania-kws2100-2024/kristiania-kws2100-2024.github.io#3]
https://github.com/kristiania-kws2100-2024/kristiania-kws2100-2024.github.io/blob/8b91b3111e2cafa9e4fd163a6f0f2d2b565d11fa/src/modules/map/useFeatures.tsx#L9

**Comment by jhannes** [comment]
Lagt inn her https://github.com/kristiania-kws2100-2024/kristiania-kws2100-2024.github.io/blob/reference/05/src/modules/map/useVectorFeatures.tsx
